#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         0
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Google-chrome desktop='^1'
#bspc rule -a Terminator desktop='^2'
bspc rule -a code-oss desktop='^3'
bspc rule -a Pavucontrol state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Lightdm-gtk-greeter-settings state=floating

/home/jisas/.config/polybar/launch.sh &
feh --bg-fill /home/jisas/Imágenes/17010.webp &
picom &
setxkbmap latam &
bspc config focus_follows_pointer true
xsetroot -cursor_name left_ptr &
xinput set-prop "ELAN0504:00 04F3:3091 Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "ELAN0504:00 04F3:3091 TouchPad" "libinput Natural Scrolling Enabled" 1
